<?php
/** @var \Advertikon\Subcat\Block\CategoryContainer $block */

$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$imageHelper = $this->helper(\Magento\Catalog\Helper\Image::class);

echo '<div class="subcat-wrapper">';

foreach ($block->getChildren() as $category) {
    $_imgUrl = $category->getImageUrl() ?: $imageHelper->getDefaultPlaceholderUrl('image');
    $html = <<<HTML
    <div class="subcat-item">
        <a href="{$category->getUrl()}" alt="{$category->getName()}">
        <div class="subcat-item-title">{$category->getName()}</div>
            <div class="category-image">
                <img src="{$block->escapeUrl($_imgUrl)}"
                    alt="{$block->escapeHtmlAttr($category->getName())}"
                    title="{$block->escapeHtmlAttr($category->getName())}" class="image" />
            </div>
        </a>
    </div>
HTML;
    echo $_helper->categoryAttribute($category, $html, 'image');
}

echo '</div>';
